baseURL = 'https://s-ramakrishnan1991.github.io/'
languageCode = 'en-us'
title = 'Sreenivas Ramakrishnan'
theme = 'PaperMod'

[params]
    env = 'production'
    description = "Sreenivas Ramakrishnan's Personal Website" # Change this
	showFullTextContent = false
	fingerprint = false
	displayFullLangName = false
	hideFooter = false
	disableThemeToggle = false
	disableScrollToTop = false
	
    # Profile Mode settings (matches the home page of the link provided)
    #[params.profileMode]
        #enabled = true
        #title = "Sreenivas Ramakrishnan"
        #subtitle = "Optical Engineer, Quantum Technology Fanatic"
        #imageUrl = "img/profile.jpg" # Place your photo in static/img/profile.jpg
        #imageWidth = 140
        #imageHeight = 200
		
    # Social links (icons at the bottom)
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/s-ramakrishnan1991"
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://linkedin.com/in/sreenivas-ramakrishnan/"
    [[params.socialIcons]]
        name = "xing"
        url = "https://www.xing.com/profile/Sreenivas_Ramakrishnan/web_profiles"
	[[params.socialIcons]]
		name = "email"
		url = "mailto:sreenivas.ramakrishnan1991@gmail.com"
	
[caches]
  [caches.images]
    dir = ':cacheDir/images'
	
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
disableDefaultLanguageRedirect = false

[languages]
  [languages.de]
    contentDir = 'content/de'
    languageName = 'Deutsch'
    weight = 1
	[[languages.de.menu.main]]
		name = "Startseite"
		url = "/de/"
		weight = 1
	[[languages.de.menu.main]]
		name = "Über mich"
		url = "/de/about/"
		weight = 2
	[[languages.de.menu.main]]
		name = "Schulungen und Zertifizierungen"
		url = "/de/training/"
		weight = 3
	[languages.de.params.profileMode]
		enabled = true
        title = "Sreenivas Ramakrishnan"
        subtitle = "Optikingenieur, Quantum Technologie Fanatiker"
		imageUrl = "img/profile.jpg"
		imageWidth = 140
        imageHeight = 200
	
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    weight = 1
	[[languages.en.menu.main]]
		name = "Home"
		url = "/"
		weight = 1
	[[languages.en.menu.main]]
		name = "About"
		url = "/about/"
		weight = 2
	[[languages.en.menu.main]]
		name = "Training and Certifications"
		url = "/training"
		weight = 3
	[[languages.en.menu.main]]
		name = "Projects"
		url = "/projects"
		weight = 4
	[[languages.en.menu.main]]
		name = "Blog"
		url = "/blog"
		weight = 5
	[languages.en.params.profileMode]
        enabled = true
        title = "Sreenivas Ramakrishnan"
        subtitle = "Optical Engineer, Quantum Technology Fanatic"
		imageUrl = "img/profile.jpg"
		imageWidth = 140
        imageHeight = 200
        